language: node_js
sudo: false
node_js:
- '8'
- '10'
- '12'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
notifications:
  irc:
    channels:
    - secure: fAl4fu/JFDyBB1RRVHNX0QcMhx/9CnGMNnPdkf47XkPBDI7Z5E9DYT651nsDUxANf6HQEiXrqVyl+cm3rphBOFBk6hlCEYpuFcCf6bYLOoBNDTqoIsU07JM6rOPRNjddrv8LYefS6Q04YmJk0ifyYLcYK8iWC52ZcEF0KIl+zVA=
    on_success: change
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: MGqXNRrUHr7Tt4z/939duLbvbeETGNL0PLv0qbhYBsG9GUvsA7E9VnSP2hDUnZnFulqHkS/gXRT79aPQ5LfHWTabqfpnZGJVnQDLyL73AdfGBL5I5KIY/TY4+0NeMeHSUWQYIabB0HhP1KOgHYyuWBUD1+0Qi/pYWN5ibBi9Tz0=
  on:
    tags: true
    repo: taskcluster/fast-azure-storage
